Repository TheeraphatStudent/pm-management, pull requests merged in 2024-08, with the labels that each got.

#8 feat: integrate member & Rain Simulator
  .gitignore
  document/Ass1_oop.pdf
  document/PM2.5 Management Documentation.docx
  document/pm2.5-test.txt
  src/components/Dashboard.java
  src/components/Devpanel.java
  src/components/Entrypagepanel.java
  src/components/Footer.java
  src/components/Statistic.java
  src/pages/EntryPage.java
  src/pages/Member.java
  src/pages/Page.java
  src/resource/colors/MainColor.java
  src/resource/environment/WindowClosingFrameEvent.java
  src/resource/images/boonisa.png
  src/resource/images/dust.jpeg
  src/resource/images/dust.png
  src/resource/images/success.png
  src/resource/images/theeraphat.png
  src/resource/images/warring.png
  src/utils/useAlert.java
  src/utils/useButton.java
  src/utils/useSourceImg.java
Labels: enhancement

#9 feat: integrated statistic
  document/pm2.5-err1.txt
  document/pm2.5-err2.txt
  document/pm2.5-err3.txt
  src/components/Dashboard.java
  src/components/Devpanel.java
  src/components/Footer.java
  src/components/Statistic.java
  src/pages/Page.java
  src/resource/colors/MainColor.java
  src/utils/useButton.java
  src/utils/usePanel.java
  src/utils/useTextPane.java
Labels: enhancement

#10 Revert "feat: integrated statistic"
  document/pm2.5-err1.txt
  document/pm2.5-err2.txt
  document/pm2.5-err3.txt
  src/components/Dashboard.java
  src/components/Devpanel.java
  src/components/Footer.java
  src/components/Statistic.java
  src/pages/Page.java
  src/resource/colors/MainColor.java
  src/utils/useButton.java
  src/utils/usePanel.java
  src/utils/useTextPane.java
Labels: help wanted

#11 Revert "Revert "feat: integrated statistic" (#10)"
  document/pm2.5-err1.txt
  document/pm2.5-err2.txt
  document/pm2.5-err3.txt
  src/components/Dashboard.java
  src/components/Devpanel.java
  src/components/Footer.java
  src/components/Statistic.java
  src/pages/Page.java
  src/resource/colors/MainColor.java
  src/utils/useButton.java
  src/utils/usePanel.java
  src/utils/useTextPane.java
Labels: good first issue

#12 feat: setup random range
  src/components/Dashboard.java
  src/components/Footer.java
  src/pages/Page.java
Labels: enhancement

#13 feature;/updatepeople
  src/components/Dashboard.java
  src/components/Footer.java
  src/components/Statistic.java
  src/pages/Page.java
Labels: enhancement

#14 feat: integrated anything
  README.md
  dockerFile
  src/components/Dashboard.java
  src/components/Footer.java
  src/components/Statistic.java
  src/pages/Page.java
  src/resource/environment/WindowEntryScreen.java
  src/resource/images/health1.png
  src/resource/images/health2.png
  src/resource/images/health3.png
  src/resource/images/health4.png
  src/utils/usePanel.java
  src/utils/useRandom.java
  src/utils/useTextarea.java
Labels: enhancement

#15 feat: comment app
  dockerFile
  src/App.java
  src/pages/EntryPage.java
  src/pages/Page.java
Labels: enhancement

#16 feat: fix random range
  document/pm2.5-err4.txt
  src/components/Dashboard.java
  src/components/Footer.java
Labels: enhancement

#17 feat: comment app
  src/components/Dashboard.java
  src/pages/EntryPage.java
  src/pages/Page.java
  src/utils/usePanel.java
  src/utils/useRandom.java
Labels: enhancement

#18 feature;comment
  src/components/Dashboard.java
  src/components/Devpanel.java
  src/pages/EntryPage.java
  src/pages/Member.java
  src/pages/Page.java
  src/resource/environment/WindowClosingFrameEvent.java
  src/utils/useButton.java
Labels: enhancement

#19 feat: fix preloaded dashboard
  src/components/Dashboard.java
Labels: enhancement

#20 feat: regex text value
  src/components/Devpanel.java
  src/components/Footer.java
  src/resource/font/KhaoklongThin.ttf
  src/utils/useTextarea.java
Labels: enhancement

#21 feat: lasted update
  src/components/Dashboard.java
  src/components/Footer.java
  src/utils/useTransform.java
Labels: enhancement
